<h2>O Pythonie</h2>

 <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Python_logo_and_wordmark.svg/240px-Python_logo_and_wordmark.svg.png"> 
 
Python to język programowania <b>wysokiego poziomu</b>. Python jest również językiem programowania <b> obiektowego </b>. To jeden z wielu dostępnych języków, w którym można nauczyć się programowania. Każdy ma swoje wady i zalety, jak również swoje szczególne przeznaczenie.

<h1>Literatura</h1>
    <ul>
    <li>A. B. Downey, J. Elkner, C. Meyers, “Think Python. How to Think Like a Computer Scientist”: http://www.greenteapress.com/thinkpython/</li>
    <li>Matthes E., "Python Crash Course: A Hands-On, Project-Based Introduction to Programming"</li>
    <li>Kurs: https://www.codecademy.com/learn/learn-python</li>
    <li>dokumentacja: https://www.python.org/</li>
    </ul>
    

<h1>Przygotowanie środowiska</h1>

Mac i UNIX: w większości dystrybucji MacOS i Unix Python jest już zainstalowany na komputerze. Nadal należy przygotować środowisko.

Windows: Należy przygotowac środowisko łącznie z instalacją języka oprogramowania.

Najlepszym wyborem jest wszystko-w-jednym jest Anaconda https://www.anaconda.com/, która instaluje język Python wraz z najpotrzebniejszymi bibliotekami

Pobieramy Anacondę dla wersji <b>2 lub 3</b>

<ol>
    <li>Instalujemy ją z pliku .exe</li>
    <li><b>Zaznaczamy "Add Anaconda to the system PATH environment variable"</b></li>
    <li>Wybieramy "Install"</li>
    <li>Po instalacji uruchamiamy Anaconda Prompt (konsola) lub Anaconda Navigator (graficzny)</li>
</ol>

Od teraz Pythnon dostępny jest na komputerze. Możemy go wywołać uruchamiając konsolę i wpisując "python" i uruchamiając jego tryb <b>interaktywny</b>. W tym trybie można wykonywać operacje na bieżąco, nie można natomiast pisać programu/skryptu. Do tego potrzebne jest nam środowisko programistyczne.


<h1>Co to jest IDE?</h1>

Integrated Development Environment to środowisko programistyczne, które służy do tworzenia, modyfikowania i testowania oprogramowania/ kodu źródłowego. Wiele firm oferuje różne środowiska, zarówno darmowe, jak również zaawanosowane płatne wersje.

IDE umozliwia między innymi:
<ul>
    <li>Szybką i wygodną edycję kodu</li>
    <li>Debugowanie kodu (śledzenie wartości zmiennych, zatrzymywanie kodu w dowolnym miejscu)</li>
    <li>Podpowiedzi nazw funkcji i zmiennych</li>
    <li>Dynamiczne sprawdzanie składni</li>
</ul>

Python domyślnie instaluje proste środowisko <b>IDLE</b>, które nie ma zbyt wielu funkcjonalności.

Anaconda domyślnie instaluje środowisko <b>Spyder</b>, które jest jednym z lepszych środowisk IDE

<img src="https://www.marsja.se/wp-content/uploads/2016/01/Spyder_object_inspetor.png.png">

<h1>Jupyter Notebook</h1>

Typ IDE, który pozwala na bieżącą edycję kodu w formie następujących linijek i jednocześnie wyświetlania poniżej ich wyników, wykresów i tabel w naprzemiennej formie kod->wynik. Jest bardzo dobrym narzędziem do testowania funkcjonalności bibliotek i nauki. Pozwala na szybką edycję kodu i wyświetlenie wyniku, <b> bez potrzeby kompilacji całego kodu ponownie </b>. Jest uruchamiany w przeglądarce internetowej.

<img src="http://i.imgur.com/100MtXR.png" width=700>

Jupyter Notebook posiada duże możliwości prezentacji kodu <b>Cała ta prezentacja jest wykonana w Jupyter Notebook z dodatkiem RISE.</b>

Aby uruchomić Jupyter Notebook wybieramy "Launch" w Anaconda Navigator lub wpsiujemy jupyter-notebook w Anaconda Prompt

START!

Zaczynamy kodować w Pythonie.

Klasycznie pierwszą linijką, nie inaczej musi być polecenie wyświetlające tekst "Hello World!"


In [3]:
print("Hello World!")

Hello World!


 Proste typy danych

Liczby

    całkowite (int)
    zmiennoprzecinkowe (float)
    złożone (complex)


In [13]:
type(3)

int

In [14]:
type(3.0)

float

In [15]:
type(1+1j)

complex

Tekst String

In [16]:
type("Tekst")

str

Typ logiczny (boolean)

In [1]:
type(True)

bool

<h1>Definicja zmiennych</h1>

Zmienną w Pythonie definiujemy przez proste przypisanie, w odróżnieniu od innych języków programowania niższych poziomów.

In [7]:
liczba = 8
print(liczba)

8


<h2> Zmienne w Pythonie są dynamiczne </h2>
Oznacza to, że możemy zmieniać typ wartości przypisanej do zmiennej

In [8]:
print(liczba)
liczba = "siedem"
print(liczba)

8
siedem


<h2>Każdy typ ma szczególne właściwości</h2>

In [14]:
a = 3
type(a)

int

In [10]:
a + a

6

In [11]:
a = "3"
type(a)

str

In [12]:
a+a

'33'

<h1>Operacje arytmetyczne</h1>
Podstawowe operacje są zdefiniowane w Pythonie bez potrzeby korzystania z zewnętrznych bibliotek

In [15]:
a + a

6

In [16]:
a - a

0

In [17]:
a * a #mnożenie

9

In [18]:
a/a

1.0

In [19]:
a**a#potęgowanie

27

In [20]:
a%a#modulo

0

<h1> Rzutowanie typów </h1>
To zmiana typu danej

In [23]:
print(type(a))
#int
type(int(a))

<class 'int'>


int

In [26]:
a = float(a)
print(type(a))
print(a)

<class 'float'>
3.0


In [28]:
a = str(a)
print(type(a))

<class 'str'>


In [36]:
a = bool(-2)
print(a)
#bool

True


<h1> Ciąg dalszy operacji na liczbach </h1>

In [38]:
a = -3 
print(abs(a))#wartosc bezwzględna

3


In [39]:
a = 3
b = 2
divmod(a,b)

(1, 1)

In [41]:
pow(3,2)
3**2

9

<h1> Błędy </h1>

Gdy pojawi się w kodzie błąd, warto spojrzeć na to co go spowodowało, by znaleźć przyczynę

In [42]:
float("Tego nie da się")

ValueError: could not convert string to float: 'Tego nie da się'

<h1> Importowanie bibliotek </h1>

Biblioteki zawierają dodatkowe funkcjonalności, klasy i typy danych.
Biblioteki można importować na 3 sposoby:

In [52]:
import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

In [49]:
from numpy import *
arange(5)

array([0, 1, 2, 3, 4])

In [51]:
from numpy import arange
ones(5)

array([1., 1., 1., 1., 1.])


Dokumentacja bilbioteki math: https://docs.python.org/2/library/math.html


<h2> Indeksowanie </h2>

Indeksowanie pozwala na pobranie wartości obiektu złożonego - ze znaków, z wartości lub z innych obiektów.

<b>Indeks w Pythonie liczymy od zera</b>

In [54]:
s = "Monty Python" #tekst
s[1]

'o'

In [56]:
s[-3]#Od końca

'h'

In [57]:
len(s)

12

In [59]:
val = 232 #liczby
val[0]

TypeError: 'int' object is not subscriptable

<h2> Wycinki </h2>
Podobnie do indeksowania pozyskują wartości, z tą różnicą że pobieramy wybrany fragment

In [60]:
s = "Monty Python"

In [66]:
s[3:6]
#od początku

'ty '

In [67]:
s[4:]#do końca

'y Python'

In [71]:
s[::2]#co drugi

'MnyPto'

In [78]:
s[::-2]#od końca?

'nhy to'

 Typy typowe dla Pythona

Python oferuje wiele dodatkowych typów danych, zwłaszcza za pośrednictwem bibliotek. Kilka z nich jest wbudowane w język i są bardzo użyteczne, a ich znajomość ułatwia pracę. Są to:

    Listy
    Słowniki
    Krotka
    Zbiór


<h2>Listy</h2>
Pozwalają przechowywać wiele elementów, <b>dowolnego</b> typu, są modyfikowalne i zachowują kolejność elementów
Definiuje się je przez []

In [83]:
lista1 = [1,2,8,4,21]
print(type(lista1))
lista2 = ["2","trzy","a"]
print(type(lista2))#lista str


<class 'list'>
<class 'list'>


In [86]:
lista3 = [1,"tekst",True,2.3]
print(lista3)

[1, 'tekst', True, 2.3]


In [87]:
lista4 = [lista3,lista2,[lista1,2]]
lista4

[[1, 'tekst', True, 2.3], ['2', 'trzy', 'a'], [[1, 2, 8, 4, 21], 2]]

<h3> Indeksowanie w listach </h3>

In [96]:
listcepcja = [1,[3,4],'dwa',['zaraz zagnieździmy',['kolejne gniazdo']]]
listcepcja[3][1][0][3]

'e'

In [30]:
#kolejne gniazdo

<h3> Modyfikacja listy - dodawanie i zmiana elementów</h3>

In [103]:
lista1[3:5] = [12,13]
print(lista1)

[1, 2, 8, 12, 13]


In [104]:
lista1.append(100)
print(lista1)

[1, 2, 8, 12, 13, 100]


In [109]:
lista1[2] = lista1[2]**2
print(lista1)

[1, 2, 64, 12, 13, 100, 121]


<h3> Modyfikacja listy - usuwanie elementów</h3>

In [113]:
lista = [1,2,3,4,21]
print(lista.remove(3))
print(lista)#remove

None
[1, 2, 4, 21]


In [115]:
print(lista.pop(3))
print(lista)

21
[1, 2, 4]


<h3> Przeszukiwanie list </h3>

In [117]:
lista = [10,20,30]
print(30 in lista)

True


In [118]:
print(lista.index(30))

2


<h2> Krotki</h2>
    Są jak listy...z tą różnicą że nie są modyfikowalne
    Definiujemy je poprzez ()

In [120]:
krotka1 = (2,"da",4)
type(krotka1)

tuple

In [124]:
krotka1[:2]

(2, 'da')

In [134]:
nowa_lista = list(krotka1)
nowa_lista[0] = 4
print(tuple(nowa_lista))

(4, 'da', 4)


<h2>Zbiory</h2>
Przechowują dane, są niemodyfikowalne, nie zachowują kolejności, przechowują tylko <b>unikalne</b> elementy

In [135]:
zbior = set([3,4,5,6])
type(zbior)

set

In [144]:
lista = [1,2,3,3,4,5,6,4,2,4,3,2,1,43,2]
len(set(lista))

7

In [150]:
zbior1 = set([1,2,3])
zbior2 = set([3,4,5])
zbior2.difference(zbior1)

{4, 5}

In [44]:
#intersection

<h2>Słowniki</h2>
Słowniki jeden z najważniejszych typów wbudowanych Pythona. Opisuje on związek par wartość - klucz. 
Słownik nie zachowuje kolejności elementów. Definiuje się go za pomocą {}

In [152]:
a = {2: 3, "klucz1": 10}

<class 'dict'>


In [153]:
a[0]

KeyError: 0

<h3>Indeksowanie</h3>

In [155]:
a["klucz1"]

100

<h3> Modyfikacje </h3>

In [156]:
a["klucz1"] = 200
print(a)

{2: 3, 'klucz1': 200}


In [158]:
a["klucz2"] = 300
print(a)

{2: 3, 'klucz1': 200, 'klucz2': 300}


<h3> Dostęp do wartości i kluczy </h3>

In [159]:
a.keys()

dict_keys([2, 'klucz1', 'klucz2'])

In [160]:
a.values()

dict_values([3, 200, 300])

In [161]:
a.items()

dict_items([(2, 3), ('klucz1', 200), ('klucz2', 300)])

<h1> Sekwencje </h1>
Sekwencje pozwalają na iterację poprzez pewien ciąg wartości - na przykład znaków, liczb i dokonywania na nich operacji.

<h2> Sekwencyjne typy danych </h2>
To takie typy, które dopuszczają iterację poprzez ich elementy. Są to:
<ul>
    <li>listy</li>
    <li>krotki</li>
    <li>tekst</li>
    <li>sekwencje binarne</li>
</ul>

Istnieje także (bardzo często używany) generator sekwencji, który jest funkcją: range() oraz xrange()

<h2> Operacje na sekwencjach</h2>

In [172]:
100 in [0,100,200]

True

In [173]:
100 not in [0,100,200]

False

In [175]:
[0,10,20] * 2

[0, 10, 20, 0, 10, 20]

<h3> Funkcje wbudowane dla sekwencji </h3>
len - długość sewencji
min, max - najmniejszy i największy element

In [184]:
lista1 = "python$"
min(lista1)

'$'

<h2> Co wyrożnia Pythona?</h2>

Jego czytelność jest wynikiem praktycznego i funkcjonalnego wdrożenia konwencji z innych języków programowania - mianowice <b> wcięć </b>

Każdy fragment kodu, który jest podrzędny <b> musi </b> (w innych językach jest to mile widziane, ale nie jest konieczne) być wcięty <b> tabulatorem lub 4 spacjami </b>

Wcięcia te informują interpreter kiedy dany blok kodu się kończy.

<h1> Iteracje - pętle for i while (na sekwencjach) </h1>

Pętle tworzą tzw. iteratory, które iterują się przez sekwencję zwracając każdorazowo <b> kolejne </b> elementy

<h2> Pętla for </h2>
Jej konstrukcja jest nastepująca

for <i>nazwa_iteratora</i> in <i>nazwa_sekwencji</i>:

    rób coś

In [186]:
lista1 = [0,1,2]
for x in lista1:
    print(x)
    
print(x)

0
1
2
2


In [60]:
#w liscie

In [61]:
#w range

In [62]:
#podwojna

<h2> Pętla while </h2>
Pętla for wykonuje się dopóki sekwencja nie dobiegnie końca. Pętla while wykonuje się dopóki podany warunek jest spełniony.

Konstrukcja

while <i> warunek </i>:

    ~rób coś~
    
Należy uważać, gdyż warunek może nie zostać spełniony nigdy, a kod utknie w pętli!

In [63]:
#while

<h1> Operatory porównań </h1>

Wprowadzenie pętli while doprowadziło nas do momentu w którym warto wspomnieć czym są operatory porównań.
Są to (jak w matematyce) operatory, które służą do uzyskania wartości boolean z porównania dwóch zmiennych. Rezultatem jest zatem True lub False

In [64]:
#rownosc

In [65]:
#nierownosc dokladna

In [66]:
#wiekszy niz

In [67]:
#wiekszy rowny

<h1> Kontrola przepływu - if, elif, else </h1>
Instrukcje warunkowe if służą do kontroli przepływu poprzez narzucanie warunków na kod.
Struktura to

if <i> warunek </i>:

    rób coś
elif <i> warunek </i>:

    rób coś
else:

    rób coś

In [69]:
#if

In [70]:
#rozbity if

W konstrukcjach z iteratorami oraz pętlami przydatne są też operacje break, end, pass

In [71]:
#break, end, pass

<h1> Interakcja w konsoli </h1>
Polecenie input() pozwala na wprowadzanie wartości w trakcie wykonywania programu. Funkcja tak przydatna jest podczas tworzenia programów operujących w konsoli, a również do testowania kodu w różnych warunkach.

In [72]:
for a in range(2):
    x = input()
    print(float(x)+a) #bo input jest zawsze tekstem!

20
20.0
20
21.0


<h1>Funkcje vs. Metody</h1>

Właśnie wykorzystaliśmy <b>funkcję</b> wyświetlania "print". Python oferuje również metody. Czym się one różnią?

<img src="https://d2h0cx97tjks2p.cloudfront.net/blogs/wp-content/uploads/sites/2/2018/02/Python-Functions-vs-Methods-01-1024x536.jpg">

<h1>Funkcje</h1>

Funcje mają strukturę (syntax) następującej postaci:

<i><b>nazwa</b>(parametr_1,parametr_2,...,parametr_n)</i>

Wyróżniamy <b>funkcje wbudowane</b> i <b> funkcje zdefiniowane przez użytkownika</b>.

Funkcje wbudowane są dostepne poprzez wywołanie ich nazwy wprost w kodzie (dostępne tu: https://docs.python.org/2/library/functions.html). Przykładem takiej funkcji jest <b>print()</b>

Funkcje definiowane przez użytkownika pozwalają na utworzenie nowej funkcjonalności (zajmiemy się nimi później)

<h1> Metody </h1>

Python jest językiem programowania <b> obiektowego </b>. Oznacza to, że wszystko w nim jest <b>obiektem</b>, który ma swoje właściwości, takie jak atrybuty i metody (o tym dokładniej w dalszej części wykładów).

Metody wywoływane są zatem na <b>obiektach</b>. Ich syntax to:
<i><b>nazwa_obiektu</b>.nazwa_metody(parametr_1,parametr_2,...,parametr_n)</i>

Istnieje w języku kilka wbudowanych obiektów, które posiadają wbudowane metody. Przykładem wbudowanych obiektów są typy danych.

<h1>Klasy</h1>
Żeby zrozumieć istotę działania metod i ich różność od funkcji, przyjrzyjmy się czym jest obiekt.

Obiekt to <b>wszystko</b> co napiszemy w Pythonie. To zarówno klasy jak i funkcje.

Spotkamy się z metodami przypisanymi do klas. Klasa to bardzo ważny element języków obiektowych.


<h2>Czym zatem jest klasa?</h2>

<b>Klasa</b> to <i>abstrakcja</i> pewnego obiektu. Oznacza to uogólnieniony opis pewnego elementu, który zdefiniowany jest przez taką klasę poprzez określenie jego typowych <b>cech (atrybutów) i operacji (metod), które można na nim wykonać</b>. Tą samą strukturą opisujemy elementy świata rzeczywistego.
    
Przykład obrazujący:

<b>Pies</b> to abstrakcyjna klasa, którą opisujemy podgatunek zwierzącia.
Ma cechy (atrybuty):
<ul>
    <li>Kolor sierści</li>
    <li>Waga</li>
    <li>Imie</li>
</ul>

Oraz metody:
<ul>
    <li>Jedz</li>
    <li>Siad</li>
    <li>Waruj</li>
</ul>

<h1>Instancja</h1>

To praktyczna realizacja klasy.

Kontynuując przykład obrazujący:

Adoptując psa nadajemy mu atrybuty - imie (Bobby) i opisujemy jego cechy (sierść brązowa, waga 6kg). Wtedy otrzymujemy <b> instancję</b> klasy pies w postaci <i>Bobby</i>.

Teraz możemy wywołać metodę na naszej instancji, która zdefiniowana już jest w klasie:

pies.waruj()

In [11]:
from IPython.display import Image
Image(url = "01-uml-base-class-and-object-explained.png")

Wracając zatem do metod i funkcji.

print() to funkcja

In [12]:
a = "pies"
a.upper() #a to metoda klasy

'PIES'

<h2> Funkcje </h2>
Istnieje możliwość definiowania własnych funkcji.

Tworzą one "wywoływalne bloki instrukcji".

Są szczególnie przydatne gdy używamy pewnego fragmentu kodu <b>wielokrotnie</b>

Mogą (nie muszą) przyjmować parametry/argumenty

Mogą (nie muszą) zwracać obiekt

<h3> Definicja funkcji </h3>

In [ ]:
def nazwa_funkcji(argumenty):
    instrukcje
    ...
    return obiekt

Pamiętamy o wcięciu 4 spacjami lub tabulatorem!

<h3>Przykład "Hello World!"</h3>

<h3>Wykorzystanie argumentów funkcji</h3>

In [73]:
def suma(a,b):
    return a+b

suma(4,3)

7

In [74]:
#odejmowanie

<h3> Argumenty ze słowem kluczowym </h3>
Argumenty można podzielic na pozycyjne i kluczowe.

In [75]:
#pozycyjne

In [76]:
#zamiana

In [77]:
#kluczowe

In [78]:
#zamiana

In [79]:
#kolejnosc

<h3>Domyślne agrumenty</h3>

In [80]:
#domyślne

<h3> Zagnieżdżanie funkcji </h3>

In [81]:
def srednia(*args):
    return sum(args)/len(args)

def suma_srednich(lista1,lista2):
    return srednia(*lista1) + srednia(*lista2)
    
suma_srednich([1,2,3],[4,6,8])

8.0

<h3> Rekurencja funkcji </h3>

In [82]:
def rekurencja(n):
    if n == 0: return 0
    elif n == 1: return 1
    else: return rekurencja(n-1)+rekurencja(n-2)

[rekurencja(n) for n in range(12)]

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

<h2>Zmienne globalne</h2>

Można definiować zmienne globalne, które dostępne są dla wszystkich funkcji

In [84]:
globalna = "globalna"

def f1(tekst):
    return tekst + globalna
    
def f2(tekst):
    globalna = "globalna zmieniona w funkcji"
    return tekst + globalna

In [85]:
#po

# Macierze

---

Język python sam w sobie nie obsługuje działania na macierzach dlatego korzystamy ze specjalnej biblioteki numpy, której zadaniem jest przygotowanie pythona do operacji na "macierzach".

Pakiet numpy jest używany w większości analiz numerycznych w Pythonie. To pakiet zawierający wydajne środowisko do pracy nawektorach, macierzach i strukturach wielowymiarowych. Biblioteka została zaimplementowana w języku C oraz Fortranie co sprzyja szybkości działania algorytmów.

In [1]:
# stwórzmy macierz

## Po co mi macierze przecież są typy sekwencyjne ?

- Lista w Pythonie jest bardzo ogólna, może zawierać obiekty dowolnego typu, sa dynamicznie typowane
- Listy nie posiadają metod matematycznych i algebraicznych
- Macierze są jednolite
- Macierze są efektywne (szczególnie na pamięci i operacji numerycznych)
- Implementacja operacji w C i Fortranie przyspiesza pracę

In [2]:
import numpy as np

# Tworzenie macierzy

Istnieje kilka opcji na tworzenie/inicjalizowanie macierzy

In [3]:
x1d = np.array([0,1,2,3]) #1D
x2d = np.array([[0,1,2],[0,1,2]]) #2Db

In [4]:
x1d.shape, x2d.shape # Wektor 1D a Macierz 2D

((4,), (2, 3))

In [5]:
x1d.size, x2d.size

(4, 6)

In [6]:
x1d.ndim, x2d.ndim

(1, 2)

## List czy Tuple ?

In [7]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
x = np.array(((1,2,3),(4,5,6)))
print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [8]:
# arange(start,end,step)

In [9]:
# linspace(start,end,number of points)

In [10]:
# ones, zeros, eye, diag, empty

## Indeksy i przycinanie
* Indexing and slicing (indeksowanie i krajanie na plastry(Google translate)/ziomki na plastry/plasterkowanie)

Indeksowanie i przynacie macierzy odbywa się w ten sam sposób co w przyupadku prostych typów sekwencyjnych

In [12]:
a = np.arange(10)
print(a)
print(a[0])
print(a[::-1]) # odwrotnie
print(a[2:6:2]) # od 2 do 6 ze skokiem 2

[0 1 2 3 4 5 6 7 8 9]
0
[9 8 7 6 5 4 3 2 1 0]
[2 4]


In [13]:
np.set_printoptions(precision=2)

a=np.random.rand(3,3)
print(a)
print(a[(1,1)]) # trzy sposoby
print(a[1]) # sam wiersz
print(a[:,0]) # sama kolumna

[[0.66 0.48 0.12]
 [0.51 0.91 0.64]
 [0.04 0.75 0.41]]
0.9075996126566848
[0.51 0.91 0.64]
[0.66 0.51 0.04]
